language: go

go:
  - 1.8

sudo: required

services:
  - docker

notifications:
  email: false

install:
  - go get -u github.com/codegangsta/negroni
  - go get -u github.com/gorilla/mux
  - go get -u github.com/unrolled/render
  - go get -u github.com/mattn/go-sqlite3

script:
  - docker build --rm -t wilsonzhong/testdocker .

before_install:
  - openssl aes-256-cbc -K $encrypted_5fbf7abaab3f_key -iv $encrypted_5fbf7abaab3f_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts: 104.236.150.212

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker tag wilsonzhong/testdocker:latest wilsonzhong/testdocker:latest
  - docker push wilsonzhong/testdocker:latest
  - ssh root@104.236.150.212 "cd ~/TestDocker && sh ./update.sh"


